### ISSUE TITLE
SPIKE: Nexus Helm Chart : Investigate Potential Blockers Given This Documentation.

### ISSUE THREAD

**Issue by anthonywendt** [defenseunicorns/uds-capability-nexus#11]
Does [this](https://repo1.dso.mil/big-bang/product/packages/nexus/-/blob/main/chart/README.md) information present issues for the use of this chart?

Snippit of doc.

⚠️ Archive Notice
As of October 24, 2023, we will no longer update or support this Helm chart.
Deploying Nexus Repository in containers with an embedded database has been known to corrupt the database under some circumstances. We strongly recommend that you use an external PostgreSQL database for Kubernetes deployments.
If you are deploying in AWS, you can use our [AWS Helm chart](https://github.com/sonatype/nxrm3-helm-repository/tree/main/nxrm-aws-resiliency) to deploy Nexus Repository in an EKS cluster.
We do not currently provide Helm charts for on-premises deployments using PostgreSQL. For those wishing to deploy on premises, see our [Single Data Center On-Premises Deployment Example Using Kubernetes documentation](https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability/single-data-center-on-premises-deployment-example-using-kubernetes) for information and sample YAMLs to help you plan a resilient on-premises deployment.

Nexus Repository
[Nexus Repository OSS](https://www.sonatype.com/nexus-repository-oss) provides universal support for all major build tools.

Store and distribute Maven/Java, npm, NuGet, Helm, Docker, p2, OBR, APT, Go, R, Conan components and more.
Manage components from dev through delivery: binaries, containers, assemblies, and finished goods.
Support for the Java Virtual Machine (JVM) ecosystem, including Gradle, Ant, Maven, and Ivy.
Compatible with popular tools like Eclipse, IntelliJ, Hudson, Jenkins, Puppet, Chef, Docker, and more.

Efficiency and Flexibility to Empower Development Teams

Streamline productivity by sharing components internally.
Gain insight into component security, license, and quality issues.
Build off-line with remote package availability.
Integrate with industry-leading build tools.

Introduction
This chart installs a single Nexus Repository instance within a Kubernetes cluster that has a single node (server) configured. It is not appropriate for a resilient Nexus Repository deployment. Refer to our [resiliency documentation](https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability) for information about resilient Nexus Repository deployment options.
Use the checklist below to determine if this Helm chart is suitable for your deployment needs.

When to Use This Helm Chart
Use this Helm chart if you are doing any of the following:

Deploying either Nexus Repository Pro or OSS to an on-premises environment with bare metal/VM server (Node)
Deploying a single Nexus Repository instance within a Kubernetes cluster that has a single Node configured

Note: If you are using Nexus Repository Pro, your license file and embedded database will reside on the node and be mounted on the container as a Persistent Volume (required).

When Not to Use This Helm Chart
Do not use this Helm chart and, instead, refer to our [resiliency documentation](https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability) if you are doing any of the following:

Deploying Nexus Repository Pro to a cloud environment with the desire for automatic failover across Availability Zones (AZs) within a single region
Planning to configure a single Nexus Repository Pro instance within your Kubernetes/EKS cluster with two or more nodes spread across different AZs within an AWS region
Using an external PostgreSQL database

Note: A Nexus Repository Pro license is required for our resilient deployment options. Your Nexus Repository Pro license file must be stored externally as either mounted from AWS Secrets/Azure Key Vault in AWS/Azure deployments or mounted using Kustomize for on-premises deployments (required).

Note: We do not currently provide Helm charts for our resilient deployment options.

**Comment by missionmarc** [comment]
@mjnagel @blancharda @anthonywendt Based on the answer back from Big Bang can we consider this closed?
